name: Task
description: | 
  Write up a new task for development of the doctest test adapter.
  This is not a bug or a feature proposal.
  Should only be used by developers on this project.
title: "[DTA] [TASK] - Describe task briefly "
labels: [enhancement, triage]
assignees: comfyjase

body:
    - type: markdown
      attributes:
        value: |
          - Please make sure there isn't any existing [open](https://github.com/comfyjase/DoctestTestAdapter/issues) issues that might be considered a duplicate of this task.
          
    - type: textarea
      attributes:
        label: Describe the Task
        description: |
          - Brief description for the task.
          - What work roughly will be involved for this task?
      validations:
        required: true
