name: Windows Build
on: workflow_call

env:
  SOLUTION_FILE_PATH: .
  
concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true
  
jobs:
  build-windows:
    runs-on: "windows-latest"
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Debug
            configuration: Debug
            tests: true
            upload-artifact: true

          - name: Release
            configuration: Release
            tests: true
            upload-artifact: true
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Setup Workflow Variables
        id: vars
        run: | 
          echo "BUILD_TIME=$(date +'%Y.%m.%d-%H.%M.%S')" >> $env:GITHUB_OUTPUT
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT
    
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
  
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore Packages
        run: nuget restore DoctestTestAdapter.sln

      - name: Build Solution
        run: msbuild DoctestTestAdapter.sln -t:rebuild -property:Configuration=${{ matrix.configuration }}

      - name: Unit Tests
        if: ${{ matrix.tests }}
        run: dotnet test "./DoctestTestAdapter.Tests/bin/${{ matrix.configuration }}/DoctestTestAdapter.Tests.dll"

      - name: Upload Artifact
        if: ${{ matrix.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: Windows-${{ matrix.configuration }}-${{ steps.vars.outputs.BUILD_TIME }}-${{ github.ref_name }}-${{ steps.vars.outputs.SHA_SHORT }}
          path: DoctestTestAdapter.VSIX/bin/${{ matrix.configuration }}/
          retention-days: 30
